In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import sys
import numpy as np

import matplotlib as mpl
sys.path.insert(1, "/home/dima/Projects/NNCompression")
from pathlib import Path
import torch.nn as nn

In [2]:
from study.configs.config_base import StudyConfig
from study.study import Study
import models.spsa as spsa
from importlib import reload

In [3]:
reload(spsa)

<module 'models.spsa' from '/home/dima/Projects/NNCompression/models/spsa.py'>

In [4]:
study_config = Study.study_initialize()

/home/dima/miniconda3/envs/wsdm/lib/python3.12/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'template': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)


In [5]:
study_config.training_config.epoch = 5
study_config.training_config.evaluate_step = 2
study_config.reruns = 3
study_config.training_config.dataset = "FashionMNIST"
# study_config.training_config.gpu = "cpu"
study_config.training_config.model = "LeNet3_3"
study_config.training_config.optimizer_type = "spsa"


study_config.perturb_regularization_config.is_perturb_reg = True

study_config.perturb_regularization_config.perturb_loss_mult = 0.1
study_config.is_record_loss = True

In [6]:
runner_config = study_config.make_runner_config_dict()

In [7]:
reload(spsa)

<module 'models.spsa' from '/home/dima/Projects/NNCompression/models/spsa.py'>

In [8]:
s = spsa.SPSA(
    runner_config["net"],
    nn.CrossEntropyLoss(reduction="none"),
    runner_config["device"],
    0.001,
    0.01,
    1
)

In [9]:
s.spsa_params

tensor([-0.0015,  0.1073, -0.1646,  ..., -0.0567,  0.0278,  0.0042],
       device='cuda:0')

In [19]:
s.step(runner_config["dataset"].data_loaders[0])

Initital params
0.008344623060592481
0.00030992098232155677
tensor([ 1.,  1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
Perturb forward
tensor([ 0.0083,  0.0083,  0.0083,  ..., -0.0083, -0.0083,  0.0083],
       device='cuda:0')
tensor([ 0.0069,  0.1157, -0.1563,  ..., -0.0651,  0.0194,  0.0125],
       device='cuda:0')
tensor(2.3076, device='cuda:0')
Perturb backward
tensor([-0.0098,  0.0990, -0.1730,  ..., -0.0484,  0.0361, -0.0042],
       device='cuda:0')
tensor(2.3042, device='cuda:0')
Central difference
tensor([ 0.2046,  0.2046,  0.2046,  ..., -0.2046, -0.2046,  0.2046],
       device='cuda:0')


In [20]:
s.spsa_params

tensor([-0.0015,  0.1073, -0.1647,  ..., -0.0567,  0.0278,  0.0041],
       device='cuda:0')

In [12]:
s.spsa_params.std()

tensor(0.0761, device='cuda:0')